server:
  port: 80

logging:
  level:
    root: WARN
    pov: INFO

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
# Add other prod-specific configurations here
