@startuml
participant SafeServiceTest
participant SafeAcctService
participant SafeSecurityService
participant SafeAgreementService
participant TxSafeCache
participant MtwTx001TxDoc
participant MtwTx001TxService
participant DataCheckAspect

SafeServiceTest -> SafeAcctService: getSafeAcctList()
SafeServiceTest <-- SafeAcctService: SafeAcctListEntry
SafeServiceTest -> TxSafeCache: addSafeDataEntry(SafeAcctListEntry)

SafeServiceTest -> SafeSecurityService: getList()
SafeServiceTest <-- SafeSecurityService: SafeSecurityListEntry
SafeServiceTest -> TxSafeCache: addSafeDataEntry(SafeSecurityListEntry)

SafeServiceTest -> SafeAgreementService: getList()
SafeServiceTest <-- SafeAgreementService: SafeAgreementListEntry
SafeServiceTest -> TxSafeCache: addSafeDataEntry(SafeAgreementListEntry)

SafeServiceTest -> MtwTx001TxDoc: create()
SafeServiceTest -> MtwTx001TxDoc: setAcctNo("1234567890")
SafeServiceTest -> MtwTx001TxDoc: setSecurityType("OTP")
SafeServiceTest -> MtwTx001TxDoc: setAgreementTypes("AGREE1,AGREE2")

SafeServiceTest -> MtwTx001TxService: doTransaction(txDoc)
activate DataCheckAspect
DataCheckAspect -> TxSafeCache: validate(txDoc)
TxSafeCache -> TxSafeCache: getDataFromTxDoc()
TxSafeCache -> ISafeDataEntry: isValid(data)
alt validation successful
  DataCheckAspect -> MtwTx001TxService: proceed()
else validation failed
  DataCheckAspect --> SafeServiceTest: throw SafeException
end
deactivate DataCheckAspect

@enduml